# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'
require 'email_spec/cucumber'
require 'action_mailer_cache_delivery'
require_relative 'wait_helpers'

# Initialize cache delivery method to prevent nil file handle issues
if defined?(ActionMailer::CacheDelivery)
  ActionMailer::Base.add_delivery_method :cache, ActionMailer::CacheDelivery
end

# Capybara defaults to CSS3 selectors rather than XPath.
# If you'd prefer to use XPath, just uncomment this line and adjust any
# selectors in your step definitions to use the XPath syntax.
# Capybara.default_selector = :xpath

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
begin
  # Use truncation strategy consistently to avoid "Table definition has changed" errors
  # Exclude final_verses table to preserve FinalVerse data
  DatabaseCleaner[:active_record].strategy = :truncation, {except: %w[final_verses ar_internal_metadata]}
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

# Optimized database cleaning strategy for better performance
Around do |scenario, block|
  # Disable background jobs during tests to prevent interference
  ActiveJob::Base.queue_adapter = :test
  
  # Use transaction strategy for non-JavaScript scenarios (much faster)
  # Use truncation only for JavaScript scenarios that need it
  if scenario.source_tag_names.include?('@javascript')
    DatabaseCleaner[:active_record].strategy = :truncation, {
      except: %w[final_verses ar_internal_metadata schema_migrations]
    }
  else
    DatabaseCleaner[:active_record].strategy = :transaction
  end
  
  # Use the cleaning block pattern for automatic cleanup
  DatabaseCleaner[:active_record].cleaning do
    block.call
  end
end

# Ensure proper Capybara reset between scenarios
After do |scenario|
  # Reset sessions and cookies
  Capybara.reset_sessions!
  
  # Clear any browser cookies if using Selenium
  if Capybara.current_driver == :selenium_chrome_headless
    page.driver.browser.manage.delete_all_cookies rescue nil
  end
  
  # Reset to default driver
  Capybara.use_default_driver
  
  # Clear ActionMailer deliveries
  ActionMailer::Base.deliveries.clear if defined?(ActionMailer)
end

# You may also want to configure DatabaseCleaner to use different strategies for certain features and scenarios.
# See the DatabaseCleaner documentation for details. Example:
#
#   Before('@no-txn,@selenium,@culerity,@celerity,@javascript') do
#     # { :except => [:widgets] } may not do what you expect here
#     # as Cucumber::Rails::Database.javascript_strategy overrides
#     # this setting.
#     DatabaseCleaner[:active_record].strategy = :truncation
#   end
#
#   Before('~@no-txn', '~@selenium', '~@culerity', '~@celerity', '~@javascript') do
#     DatabaseCleaner[:active_record].strategy = :transaction
#   end
#

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation

# Use rack_test for faster tests, selenium for JavaScript tests
Capybara.default_driver = :rack_test
Capybara.javascript_driver = :selenium_chrome_headless

# Configure webdrivers to automatically manage driver versions
require 'webdrivers'

# Additional Capybara optimizations for speed
Capybara.server = :puma, { Silent: true } # Reduce server output noise
Capybara.asset_host = 'http://localhost:3000' # Avoid asset compilation in tests

# Disable CSS and image loading for faster tests (when not testing visual elements)
Capybara.automatic_reload = false # Don't reload page between actions
Capybara.threadsafe = true # Enable threadsafe mode for parallel execution

