# Run these commands after machine is running
#
# docker-compose run web rake db:create
# docker-compose run web rake db:schema:load
# docker-compose run web rake db:seed

version: '2'

services:
  db:
    image: mysql:5
    environment:
      - "MYSQL_ROOT_PASSWORD=demo"
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
  web:
    build: .
    depends_on:
      - db
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'

