# Run these commands after machine is running
#
# docker-compose run web rake db:create
# docker-compose run web rake db:schema:load
# docker-compose run web rake db:seed
#
# OR
#
# docker-compose run web bundle exec rake db:setup 
# docker-compose run web bundle exec rake ts:index
#
# Generate list of popular verses: /utils/update_popular_verses

version: '2'

#============================================================
# Services
#============================================================
services:

  db:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=demo
      - DB_NAME=memverse_development
    volumes:
      - memverse-mysql:/var/lib/memverse/data
    networks:
      - back-tier
    ports:
      - "3306"

  redis:
    image: redis:alpine
    ports: 
      - "6379"
    networks:
      - back-tier

  memcache:
    image: memcached:1.4
    networks:
      - back-tier

  search:
    build: https://github.com/avitus/sphinx-alpine-docker.git
    ports: 
      - "9306"
      - "9312"
    links:
      - db
    networks:
      - back-tier

  web:
    build: .
    environment:
      - RAILS_ENV=development
      - DOCKERIZED=true
    env_file: 
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app    
    links:
      - redis
      - db
      - search
      - memcache
    networks:
      - front-tier
      - back-tier
    command: bundle exec rails s -p 3000 -b '0.0.0.0'

#============================================================
# Volumes
#============================================================
volumes:
  memverse-mysql:

#============================================================
# Networks
#============================================================
networks:
  front-tier:
  back-tier:

