version: 2
jobs:
   build:
     docker:
       - image: circleci/ruby:2.3
     steps:
       - checkout
       - run: echo "hello world"

# database: 
#   post:
#     - sudo cp ./config/environments/sphinx.conf /etc/sphinxsearch/sphinx.conf
#     - sudo sed -i -e 's,START=no,START=yes,' /etc/default/sphinxsearch
#     - service sphinxsearch start