--- 
javascripts: 
- base: 
  - jquery.min
  - rails
  - jquery-ui-1.8.6.custom.min
  - jquery.quickflip
  - jquery.hoverIntent  
  - 2leveltab
  - jquery.periodicalupdater
  - jquery.jeditable
  - jquery.autocomplete
  - modernizr-1.7.min
  - jquery.shuffle
  - jquery.observe_field
  - jquery.blockUI
  - application
stylesheets: 
- base: 
  - base
  - jquery.fancybox-1.3.4
  - jquery-ui-1.7.2.custom
  - bloggity
