--- 
javascripts: 
- base: 
  - jquery-1.4.3.min
  - jquery-ui-1.8.6.custom.min
  - jrails
  - jquery.jeditable
  - application
  - dragdrop
  - prototype
  - effects
  - controls
  - jquery.updater
  - jquery.periodicalupdater
  - 2leveltab
  - jquery.quickflip
  - jquery.autocomplete  
  - sorttable
  - jquery.hoverIntent
  - jquery.observe_field
stylesheets: 
- base: 
  - base
  - 2leveltab
  - bloggity
