--- 
javascripts: 
- base: 
  - jquery-1.4
  - jquery-ui
  - jrails
  - jquery.jeditable
  - application
  - dragdrop
  - prototype
  - effects
  - controls
  - jquery.updater
  - jquery.periodicalupdater
  - 2leveltab
  - jquery.quickflip
  - jquery.autocomplete  
  - sorttable
  - jquery.hoverIntent  
stylesheets: 
- base: 
  - base
  - 2leveltab
  - bloggity  
