# This is an example of what your credentials.yml should look like
# To edit the actual credentials, run:
# EDITOR="nano" rails credentials:edit

# AWS credentials (if needed)
# aws:
#   access_key_id: 123
#   secret_access_key: 345

# Postmark email service
postmark:
  api_token: 6b4a7191-6750-46e4-95d9-72ad17c45156

# Used as the base secret for all MessageVerifiers in Rails
secret_key_base: 8e490444a530fd0bc1fc40b1e82d570d9fc080c71b4f3ac7a7fce958ac91ad8805fe5888b53823afc130e9bc90778b97ee39cda94bb83004e8aa0ef9f3af86d3