development:
  # Sqlite Settings
  # adapter: sqlite3
  # database: db/development.sqlite3
  # pool: 5
  # timeout: 5000

  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: memverse_development
  username: root
  password: [hidden]
  pool: 5
  host: localhost
  socket: /var/run/mysqld/mysqld.sock  
  
test: &TEST
  # Sqlite Settings
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

  # Mysql Settings
  # adapter: mysql
  # encoding: utf8
  # database: bort_test
  # username: root
  # password:
  # pool: 5
  
staging:
  # Mysql Settings
   adapter: mysql
   database: memverse_staging
   username: avitus
   password: [hidden]
   host: mysql.memverse.com
   pool: 5
  
production:
  # Mysql Settings
   adapter: mysql
   database: memverse_production
   username: avitus
   password: [hidden]
   host: mysql.memverse.com
   pool: 5
     

    
   
   
cucumber:
  <<: *TEST