# coding: utf-8

# Load the rails application
require File.expand_path('../application', __FILE__)

# Initialize the rails application
MemverseApp::Application.initialize!

# Translation updates must also be reflected on quick_start
# New language codes must be defined in en.yml at least

TRANSLATIONS = {
  AFR:    {name: "Afrikaans 1983 Translation", language: "af"},
  AFR53:  {name: "Afrikaans 1953 Translation", language: "af"},
  NLV:    {name: "Afrikaans Nuwe Lewende Vertaling", language: "af"},
  LUT84:  {name: "Luther Bibel (1984)", language: "de"},
  LUT:    {name: "Luther Bibel (1545)", language: "de"},
  SCH:    {name: "Schlachter 2000", language: "de"},
  NIV:    {name: "New International Version (1984)", language: "en"},
  NNV:    {name: "New International Version (2011)", language: "en"},
  NAS:    {name: "New American Standard Bible", language: "en"},
  NKJ:    {name: "New King James Version", language: "en"},
  KJV:    {name: "King James Version (Modernized/1987)", language: "en"},
  RSV:    {name: "Revised Standard Version", language: "en"},
  NRS:    {name: "New Revised Standard Version", language: "en"},
  ESV:    {name: "English Standard Version (2011)", language: "en"},
  ESV07:  {name: "English Standard Version (2007)", language: "en"},
  NLT:    {name: "New Living Translation (2007)", language: "en"},
  CEV:    {name: "Contemporary English Version", language: "en"},
  HCS:    {name: "Holman Christian Standard Bible", language: "en"},
  DTL:    {name: "Darby Translation", language: "en"},
  MSG:    {name: "The Message", language: "en"},
  AMP:    {name: "Amplified Bible (Classic Edition)", language: "en"},
  IRV:    {name: "New International Reader's Version (1998)", language: "en"},
  NCV:    {name: "New Century Version", language: "en"},
  UKJ:    {name: "Updated King James Version", language: "en"},
  GEN:    {name: "Geneva Bible", language: "en"},
  GRK:    {name: "Biblical Greek (SBLGNT)", language: "en"},
  SMP:    {name: "Scottish Metrical Psalter", language: "en"},
  SMPB:   {name: "Scottish Metrical Psalter: B", language: "en"},
  SMPC:   {name: "Scottish Metrical Psalter: C", language: "en"},
  AKJ:    {name: "Authorized King James Version (1769)", language: "en"},
  GW:     {name: "God's Word Translation", language: "en"},
  GNT:    {name: "Good News Translation", language: "en"},
  NVI:    {name: "Nueva Version Internacional", language: "es"},
  RVR:    {name: "Reina-Valera 1960", language: "es"},
  NBLH:   {name: "Nueva Biblia Latinoamericana de Hoy", language: "es"},
  LBLA:   {name: "La Biblia de las Américas", language: "es"},
  ET97:   {name: "Piibel, Vana ja Uus Testament", language: "et"},
  LSV:    {name: "Louis Segond 1910", language: "fr"},
  MGK:    {name: "Modern Greek", language: "gk"},
  HCV:    {name: "Haitian Creole Version", language: "ht"},
  TMB:    {name: "Terjemahan Baru", language: "id"},
  ICE:    {name: "Icelandic Bible (2007)", language: "is"},
  LND:    {name: "La Nuova Diodati", language: "it"},
  KRV:    {name: "Korean Revised Version", language: "ko"},
  DSV:    {name: "Statenvertaling", language: "nl"},
  HSV:    {name: "Herziene Statenvertaling", language: "nl"},
  NBV:    {name: "De Nieuwe Bijbelvertaling", language: "nl"},
  RDC:    {name: "Romanian Dumitru Cornilescu Translation", language: "ro"},
  MBB:    {name: "Magandang Balita Biblia", language: "tl"},
  TAB:    {name: "Tagalog Ang Biblia", language: "tl"},
  TCL02:  {name: "Kutsal Kitap Yeni Çeviri", language: "tr"},
  ACF:    {name: "Almeida Corrigida e Fiel", language: "pt"},
  ARC:    {name: "Almeida Revista e Corrigida", language: "pt"},
  ARA:    {name: "Almeida Revista e Atualizada", language: "pt"},
  NVP:    {name: "Nova Versão Internacional", language: "pt"},
  SPB:    {name: "Svenska Folkbibeln", language: "sv"},
  YCE:    {name: "Yoruba Bible", language: "yo"},
  CCB:    {name: "Chinese Contemporary Bible", language: "zh-CN"},
  CUVS:   {name: "Chinese Union Version (Simplified)", language: "zh-CN"},
  CUV:    {name: "Chinese Union Version (Traditional)", language: "zh-TW"},
}

MAJORS = {
    :NIV => "New International Version (1984)",
    :NAS => "New American Standard Bible",
    :NKJ => "New King James Version",
    :KJV => "King James Version (Authorized)",
    :ESV => "English Standard Version (2011)",
  }

# Because hashes retain the order in which elements were inserted,
# calling BIBLEBOOKS[:en].values[i-1] will return ith English book name.

BIBLEBOOKS = Hash.new

BIBLEBOOKS[:en] = {"Gen"=>"Genesis", "Ex"=>"Exodus", "Lev"=>"Leviticus",
  "Num"=>"Numbers", "Deut"=>"Deuteronomy", "Josh"=>"Joshua", "Judg"=>"Judges",
  "Ruth"=>"Ruth", "1 Sam"=>"1 Samuel", "2 Sam"=>"2 Samuel",
  "1 Kings"=>"1 Kings", "2 Kings"=>"2 Kings", "1 Chron"=>"1 Chronicles",
  "2 Chron"=>"2 Chronicles", "Ezra"=>"Ezra", "Neh"=>"Nehemiah", "Es"=>"Esther",
  "Job"=>"Job", "Ps"=>"Psalms", "Prov"=>"Proverbs", "Eccl"=>"Ecclesiastes",
  "Song"=>"Song of Songs", "Isa"=>"Isaiah", "Jer"=>"Jeremiah",
  "Lam"=>"Lamentations", "Ezk"=>"Ezekiel", "Dan"=>"Daniel", "Hos"=>"Hosea",
  "Joel"=>"Joel", "Amos"=>"Amos", "Obad"=>"Obadiah", "Jonah"=>"Jonah",
  "Mic"=>"Micah", "Nahum"=>"Nahum", "Hab"=>"Habakkuk", "Zeph"=>"Zephaniah",
  "Hag"=>"Haggai", "Zech"=>"Zechariah", "Mal"=>"Malachi", "Matt"=>"Matthew",
  "Mark"=>"Mark", "Luke"=>"Luke", "Jn"=>"John", "Acts"=>"Acts",
  "Rom"=>"Romans", "1 Cor"=>"1 Corinthians", "2 Cor"=>"2 Corinthians",
  "Gal"=>"Galatians", "Eph"=>"Ephesians", "Phil"=>"Philippians",
  "Col"=>"Colossians", "1 Thess"=>"1 Thessalonians", "2 Thess"=>"2 Thessalonians",
  "1 Tim"=>"1 Timothy", "2 Tim"=>"2 Timothy", "Tit"=>"Titus", "Phlm"=>"Philemon",
  "Heb"=>"Hebrews", "James"=>"James", "1 Pet"=>"1 Peter", "2 Pet"=>"2 Peter",
  "1 John"=>"1 John", "2 John"=>"2 John", "3 John"=>"3 John", "Jude"=>"Jude", "Rev"=>"Revelation"}

BIBLEBOOKS[:es] = {"Gén"=>"Génesis", "Éxod"=>"Éxodo", "Lev"=>"Levitico",
  "Núm"=>"Números", "Deut"=>"Deuteronomio", "Jos"=>"Josué", "Jue"=>"Jueces",
  "Rut"=>"Rut", "1 Sam"=>"1 Samuel", "2 Sam"=>"2 Samuel", "1 Re"=>"1 Reyes",
  "2 Re"=>"2 Reyes", "1 Cró"=>"1 Crónicas", "2 Cró"=>"2 Crónicas",
  "Esd"=>"Esdras", "Neh"=>"Nehemías", "Est"=>"Ester", "Job"=>"Job",
  "Sal"=>"Salmos", "Prov"=>"Proverbios", "Ecl"=>"Eclesiastés",
  "Cant"=>"Cantares", "Is"=>"Isaías", "Jer"=>"Jeremías",
  "Lam"=>"Lamentaciones", "Ez"=>"Ezequiel", "Dan"=>"Daniel", "Os"=>"Oseas",
  "Jl"=>"Joel", "Am"=>"Amós", "Abd"=>"Abdías", "Jon"=>"Jonás",
  "Miq"=>"Miqueas", "Nah"=>"Nahún", "Hab"=>"Habacuc", "Sof"=>"Sofonías",
  "Ag"=>"Hageo", "Zac"=>"Zacarías", "Mal"=>"Malaquías", "Mt"=>"Mateo",
  "Mc"=>"Marcos", "Lc"=>"Lucas", "Jn"=>"Juan", "Hech"=>"Hechos",
  "Rom"=>"Romanos", "1 Cor"=>"1 Corintios", "2 Cor"=>"2 Corintios",
  "Gál"=>"Gálatas", "Ef"=>"Efesios", "Fil"=>"Filipenses", "Col"=>"Colosenses",
  "1 Tes"=>"1 Tesalonicenses", "2 Tes"=>"2 Tesalonicenses",
  "1 Tim"=>"1 Timoteo", "2 Tim"=>"2 Timoteo", "Tit"=>"Tito",
  "Filem"=>"Filemón", "Heb"=>"Hebreos", "Sant"=>"Santiago", "1 Pe"=>"1 Pedro",
  "2 Pe"=>"2 Pedro", "1 Jn"=>"1 Juan", "2 Jn"=>"2 Juan", "3 Jn"=>"3 Juan",
  "Jds"=>"Judas", "Apoc"=>"Apocalipsis"}

BIBLEBOOKS[:et] = {"1Ms"=>"1. Moosese raamat", "2Ms"=>"2. Moosese raamat",
  "3Ms"=>"3. Moosese raamat", "4Ms"=>"4. Moosese raamat",
  "5Ms"=>"5. Moosese raamat", "Jos"=>"Joosua", "Km"=>"Kohtumõistjate raamat",
  "Rt"=>"Rutt", "1Sm"=>"1. Saamueli raamat", "2Sm"=>"2. Saamueli raamat",
  "1Kn"=>"1. Kuningate raamat", "2Kn"=>"2. Kuningate raamat",
  "1Aj"=>"1. Ajaraamat", "2Aj"=>"2. Ajaraamat", "Esr"=>"Esra", "Ne"=>"Nehemja",
  "Est"=>"Ester", "Ii"=>"Iiob", "Ps"=>"Psalmid (Laulud)", "p"=>"Õpetussõnad ",
  "Kg"=>"Koguja", "l"=>"Ülemlaul ", "Js"=>"Jesaja", "Jr"=>"Jeremija",
  "Nl"=>"Nutulaulud", "Hs"=>"Hesekiel", "Tn"=>"Taaniel", "Ho"=>"Hoosea",
  "Jl"=>"Joel", "Am"=>"Aamos", "Ob"=>"Obadja", "Jn"=>"Joona", "Mi"=>"Miika",
  "Na"=>"Nahum", "Ha"=>"Habakuk", "Sf"=>"Sefanja", "Hg"=>"Haggai",
  "Sk"=>"Sakarja", "Ml"=>"Malaki", "Mt"=>"Matteuse evangeelium",
  "Mk"=>"Markuse evangeelium", "Lk"=>"Luuka evangeelium",
  "Jh"=>"Johannese evangeelium", "Ap"=>"Apostlite teod",
  "Rm"=>"Pauluse kiri Roomlastele", "1Kr"=>"Pauluse 1. kiri korintlastele",
  "2Kr"=>"Pauluse 2. kiri korintlastele", "Gl"=>"Pauluse kiri galaatlastele",
  "Ef"=>"Pauluse kiri efestlastele", "Fl"=>"Pauluse kiri filiplastele",
  "Kl"=>"Pauluse kiri koloslastele",
  "1Ts"=>"Pauluse 1. kiri tessalooniklastele",
  "2Ts"=>"Pauluse 2. kiri tessalooniklastele",
  "1Tm"=>"Pauluse 1. kiri Timoteosele", "2Tm"=>"Pauluse 2. kiri Timoteosele",
  "Tt"=>"Pauluse kiri Tiitusele", "Fm"=>"Pauluse kiri Fileemonile",
  "Hb"=>"Kiri heebrealastele", "Jk"=>"Jaakobuse kiri", "1Pt"=>"Peetruse 1. kiri",
  "2Pt"=>"Peetruse 2. kiri", "1Jh"=>"Johannese 1. kiri", "2Jh"=>"Johannese 2. kiri",
  "3Jh"=>"Johannese 3. kiri", "Jd"=>"Juuda kiri", "Ilm"=>"Johannese ilmutus"} 

BIBLEBOOKS[:ko] = {"창"=>"창세기", "출"=>"출애굽기", "레"=>"레위기", "민"=>"민수기",
  "신"=>"신명기", "수"=>"여호수아", "삿"=>"사사기", "룻"=>"룻기", "삼상"=>"사무엘상",
  "삼하"=>"사무엘하", "왕상"=>"열왕기상", "왕하"=>"열왕기하", "대상"=>"역대상", "대하"=>"역대하",
  "스"=>"에스라", "느"=>"느헤미야", "에"=>"에스더", "욥"=>"욥기", "시"=>"시편",
  "잠"=>"잠언", "전"=>"전도서", "아"=>"아가", "사"=>"이사야", "렘"=>"예레미야",
  "애"=>"예레미야애가", "겔"=>"에스겔", "단"=>"다니엘", "호"=>"호세아", "욜"=>"요엘",
  "암"=>"아모스", "옵"=>"오바댜", "욘"=>"요나", "미"=>"미가", "나"=>"나훔", "합"=>"하박국",
  "습"=>"스바냐", "학"=>"학개", "슥"=>"스가랴", "말"=>"말라기", "마"=>"마태복음",
  "막"=>"마가복음", "눅"=>"누가복음", "요"=>"요한복음", "행"=>"사도행전",
  "롬"=>"로마서", "고전"=>"고린도전서", "고후"=>"고린도후서", "갈"=>"갈라디아서",
  "엡"=>"에베소서", "빌"=>"빌립보서", "골"=>"골로새서", "살전"=>"데살로니가전서",
  "살후"=>"데살로니가후서", "딤전"=>"디모데전서", "딤후"=>"디모데후서", "딛"=>"디도서",
  "몬"=>"빌레몬서", "히"=>"히브리서", "약"=>"야고보서", "벧전"=>"베드로전서",
  "벧후"=>"베드로후서", "요일"=>"요한일서", "요이"=>"요한2서", "요삼"=>"요한3서",
  "유"=>"유다서", "계"=>"요한계시록"}

BIBLEBOOKS[:yo] = {"Gẹn"=>"Genesisi", "Eks"=>"Eksodu", "Lef"=>"Lefitiku",
  "Num"=>"Numeri", "Deu"=>"Deuteronomi", "Joṣ"=>"Ìwé Joṣua",
  "A. Oni"=>"Onidajọ", "Rut"=>"Rutu", "I. Sam"=>"I. Samueli",
  "II. Sam"=>"II. Samueli", "I. A. Ọba"=>"I. Awọn Ọba",
  "II. A. Ọba"=>"II. Awọn Ọba", "I. Kro"=>"I. Kronika",
  "II. Kro"=>"II. Kronika", "Esr"=>"Esra", "Neh"=>"Nehemiah", "Est"=>"Esteri",
  "Job"=>"Jobu", "O. Daf"=>"Orin Dafidi", "Owe"=>"Ìwé Owe",
  "Oni"=>"Ìwé Oniwasu", "O. Sol"=>"Orin Solomoni", "Isa"=>"Isaiah",
  "Jer"=>"Jeremiah", "Ẹk. Jer"=>"Ẹkún Jeremiah", "Esek"=>"Esekieli",
  "Dan"=>"Danieli", "Hos"=>"Hosea", "Joel"=>"Joeli", "Amo"=>"Amosi",
  "Oba"=>"Obadiah", "Jon"=>"Jona", "Mik"=>"Mika", "Nah"=>"Nahumu",
  "Hab"=>"Habakkuku", "Sef"=>"Sefaniah", "Hag"=>"Haggai", "Sek"=>"Sekariah",
  "Mal"=>"Malaki", "Mat"=>"Matteu", "Mak"=>"Marku", "Luk"=>"Luku",
  "Joh"=>"Johannu", "Iṣe Apo"=>"Iṣe Awọn Aposteli", "Rom"=>"Awọn Ara Romu",
  "I. Kor"=>"I. Awọn Ara Korinti", "II. Kor"=>"II. Awọn Ara Korinti",
  "Gal"=>"Awọn Ara Galatia", "Efe"=>"Awọn Ara Efesu",
  "Filp"=>"Awọn Ara Filippi", "Kol"=>"Awọn Ara Kolosse",
  "I. Tes"=>"I. Awọn Ara Tessalonika", "II. Tes"=>"II. Awọn Ara Tessalonika",
  "I. Tim"=>"I. Timoteu", "II. Tim"=>"II. Timoteu", "Tit"=>"Titu",
  "File"=>"Filemoni", "Heb"=>"Awọn Heberu", "Jak"=>"Jakọbu",
  "I. Pet"=>"I. Peteru", "II. Pet"=>"II. Peteru", "I. Joh"=>"I. Johannu",
  "II. Joh"=>"II. Johannu", "III. Joh"=>"III. Johannu", "Jud"=>"Juda",
  "Ifi."=>"Ifihàn Ti Johannu"}

# Mapping name to itself; can add Chinese abbreviations later, if they exist.
BIBLEBOOKS[:zh] = {"创世记"=>"创世记", "出埃及"=>"出埃及", "利未记"=>"利未记", "民数记"=>"民数记",
  "申命记"=>"申命记", "约书亚记"=>"约书亚记", "士师记"=>"士师记", "路得记"=>"路得记", "撒母耳记上"=>"撒母耳记上",
  "撒母耳记下"=>"撒母耳记下", "列王纪上"=>"列王纪上", "列王纪下"=>"列王纪下", "历代志上"=>"历代志上",
  "历代志下"=>"历代志下", "以斯拉记"=>"以斯拉记", "尼希米记"=>"尼希米记", "以斯帖记"=>"以斯帖记", "约伯记"=>"约伯记",
  "诗篇"=>"诗篇", "箴言"=>"箴言", "传道书"=>"传道书", "雅歌"=>"雅歌", "以赛亚书"=>"以赛亚书",
  "耶利米书"=>"耶利米书", "耶利米哀歌"=>"耶利米哀歌", "以西结书"=>"以西结书", "但以理书"=>"但以理书",
  "何西阿书"=>"何西阿书", "约珥书"=>"约珥书", "阿摩司书"=>"阿摩司书", "俄巴底亚书"=>"俄巴底亚书", "约拿书"=>"约拿书",
  "弥迦书"=>"弥迦书", "那鸿书"=>"那鸿书", "哈巴谷书"=>"哈巴谷书", "西番雅书"=>"西番雅书", "哈该书"=>"哈该书",
  "撒迦利亚书"=>"撒迦利亚书", "玛拉基书"=>"玛拉基书", "马太福音"=>"马太福音", "马可福音"=>"马可福音",
  "路加福音"=>"路加福音", "约翰福音"=>"约翰福音", "使徒行传"=>"使徒行传", "罗马书"=>"罗马书",
  "哥林多前书"=>"哥林多前书", "哥林多后书"=>"哥林多后书", "加拉太书"=>"加拉太书", "以弗所书"=>"以弗所书",
  "腓立比书"=>"腓立比书", "歌罗西书"=>"歌罗西书", "帖撒罗尼迦前书"=>"帖撒罗尼迦前书", "帖撒罗尼迦后书"=>"帖撒罗尼迦后书",
  "提摩太前书"=>"提摩太前书", "提摩太后书"=>"提摩太后书", "提多书"=>"提多书", "腓利门书"=>"腓利门书",
  "希伯来书"=>"希伯来书", "雅各书"=>"雅各书", "彼得前书"=>"彼得前书", "彼得后书"=>"彼得后书", "约翰一书"=>"约翰一书",
  "约翰二书"=>"约翰二书", "约翰三书"=>"约翰三书", "犹大书"=>"犹大书", "启示录"=>"启示录"}

MEDALS = {
  :gold   => 3,
  :silver => 2,
  :bronze => 1,
  :solo   => 0
}
