development:
  secret_key_base:
 
test:
  secret_key_base:
 
production:
  secret_key_base: 'UvrfrC|Qz215,b5z2b2eFIUpDC?:tTC=_)2jiUu|%ql;b_tLH3 (g)|Li^@a HPS;YyR*i w,ySjLV/J2@yh:Lh|*;P!<T{+nEZigb&m(`Z&Mr:ui+Y[Il-p-f-@b|K.'