staging:
  pid_file: /home/andyvitus/staging.memverse.com/current/tmp/searchd.pid
  searchd_file_path: /home/andyvitus/staging.memverse.com/current/db/sphinx
production:
  pid_file: /home/andyvitus/memverse.com/current/tmp/searchd.pid
  searchd_file_path: /home/andyvitus/memverse.com/current/db/sphinx

