-- Knowledge Quiz Questions Export
-- Generated: Fri Aug 15 15:45:17 PDT 2025
-- Database: memverse_production
-- Selection: 25 MCQ Approved questions ordered by last_asked
-- These are the exact questions that would be selected by the Knowledge Quiz

SET FOREIGN_KEY_CHECKS=0;

-- MySQL dump 10.13  Distrib 5.7.33, for Linux (x86_64)
--
-- Host: localhost    Database: memverse_production
-- ------------------------------------------------------
-- Server version	5.7.33-0ubuntu0.16.04.1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table `quiz_questions`
--
-- WHERE:  id IN (1254,593,594,595,596,597,598,599,600,999,1001,1104,1105,1106,1107,1108,1110,1111,1112,1334,1335,1337,1338,2025,601)

LOCK TABLES `quiz_questions` WRITE;
/*!40000 ALTER TABLE `quiz_questions` DISABLE KEYS */;
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (593,1,1,'mcq','','What was the largest number of disciples to see Jesus at any one time after His resurrection?','More than 20','More than 50','More than 100','More than 500','D',240,57,'Life of Christ','2021-10-19',28727,NULL,'Approved',NULL,'2014-04-02 00:00:00','2021-10-19 17:08:32');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (594,1,1,'mcq','','Who carried Paul\'s letter to the Roman church from Corinth to Rome?','Priscilla','Tryphena','Persis','Phoebe','D',234,18,'People','2021-10-19',28340,NULL,'Approved',NULL,'2014-04-02 00:00:00','2021-10-19 17:09:10');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (595,1,1,'mcq','','Who said: \"Lord, do not hold this sin against them.\" ?','Paul','Stephen','Peter','John','B',240,89,'Quotations','2021-10-19',27179,NULL,'Approved',NULL,'2014-04-02 00:00:00','2021-10-19 17:09:44');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (596,1,1,'mcq','','In what town did Jesus give Bartimeus his sight?','Jericho','Bethany','Capernaum','Beersheba','A',232,21,'Miracles','2021-10-19',24637,NULL,'Approved',NULL,'2014-04-02 00:00:00','2021-10-19 17:10:24');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (597,1,1,'mcq','','Who was the prophet who was called \"baldhead\" by a group of children?','Amos','Jeremiah','Elisha','Micah','C',241,83,'People','2021-10-19',NULL,NULL,'Approved',NULL,'2014-04-02 00:00:00','2021-10-19 17:11:09');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (598,1,1,'mcq','','What mountain was given to Esau for his possession?','Mount Gerizim','Mount Seir','Mount Nebo','Mount Gilboa','B',229,38,'Geography','2021-10-19',4946,NULL,'Approved',NULL,'2014-04-02 00:00:00','2021-10-19 17:11:25');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (599,1,1,'mcq','','In Revelation John addressed seven churches. Which of the following was NOT one of them?','Sardis','Collosae','Pergamos','Philadelphia','B',242,52,'Geography','2021-10-19',30722,NULL,'Approved',NULL,'2014-04-02 00:00:00','2021-10-19 17:12:11');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (600,1,1,'mcq','','Paul delivered the great sermon from Mars\' hill at the famous Areopagus in which city?','Rome','Ephesus','Corinth','Athens','D',225,60,'Geography','2021-10-19',27548,NULL,'Approved',NULL,'2014-04-02 00:00:00','2021-10-19 17:12:49');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (601,1,1,'mcq','','What noted lawyer among the Jews was a teacher of Paul?','Gamaliel','Hillel','Shammai','Nicodemus','A',226,69,'People','2021-10-23',27710,NULL,'Approved',NULL,'2014-04-02 00:00:00','2021-10-23 23:07:48');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (999,1,1,'mcq','','Which of the following correctly describes the red dragon in Revelation 12?','7 heads; 10 horns; 10 crowns','10 heads; 7 horns; 10 crowns','7 heads; 10 horns; 7 crowns','10 heads; 7 horns; 7 crowns','C',200,29,'Prophecy','2021-10-19',30898,2,'Approved',NULL,'2014-04-02 00:00:00','2021-10-19 17:05:30');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (1001,1,1,'mcq','','Why did the LORD harden Pharaoh\'s heart so he would not let Israel go?','So they would know he was LORD.','So he could show his signs among them.','So the Israelites could tell their children how he dealt with the Egyptians.','All of the above.','D',194,72,'History','2021-10-19',1782,7811,'Approved',NULL,'2014-04-02 00:00:00','2021-10-19 17:14:01');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (1104,1,1,'mcq',NULL,'When Jesus enters Jerusalem for the last time, he is greeted with a triumphal entry and a crowd of disciples praising him. The Pharisees tell Jesus to rebuke his disciples. What is Jesus\' response?','\"These people honor me with their lips.\"','\"You have not recognized the time of God\'s coming.\"','\"The heavens declare the glory of God.\"','\"If my disciples keep quiet, the stones will cry out.\"','D',240,82,'Life of Christ','2021-10-19',25774,2,'Approved',NULL,'2014-04-15 03:34:41','2021-10-19 17:07:56');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (1105,1,1,'mcq',NULL,'What was the name of Judas Iscariot\'s father?','Simeon Iscariot','Peter Iscariot','Judas Iscariot (the First)','Simon Iscariot','D',220,35,'People','2021-10-19',26331,15021,'Approved',NULL,'2014-04-15 14:16:13','2021-10-19 17:08:53');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (1106,1,1,'mcq','','Which three disciples did Jesus take with Him to Gethsemane?','Simon, Thomas, Judas','Andrew, Thaddeus, John','Peter, James, John','Matthew, Philip, Bartholomew ','C',227,91,'People','2021-10-19',24094,8446,'Approved',NULL,'2014-04-15 14:19:28','2021-10-19 17:09:26');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (1107,1,1,'mcq',NULL,'When Jesus returned from Gethsemane the first time, the disciples had fallen asleep.  Jesus said to them, \"The _______ is willing; but the _______ is weak.\"','spirit; flesh/body','flesh/body; spirit','heart/mind; strength','strength; heart/mind','A',225,85,'Life of Christ','2021-10-19',24098,8446,'Approved',NULL,'2014-04-15 14:24:15','2021-10-19 17:10:00');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (1108,1,1,'mcq',NULL,'Similar to when we sin against God for the sake of temporary worldly pleasure, Judas Iscariot betrayed Jesus for a price in money.  How much did the chief priests pay him to betray Jesus?','10 pieces of silver','30 pieces of silver','50 pieces of silver','100 pieces of silver','B',228,89,'History','2021-10-19',24072,8446,'Approved',NULL,'2014-04-15 14:29:20','2021-10-19 17:10:39');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (1110,1,1,'mcq','','At the Last Supper, how did Jesus refer to the disciple who would betray Him?','As \"the one who kisses Me\"','As \"the one who was by the fire when the rooster crowed the third time\"','As \"Judas Iscariot\"','As \"the one who dipped his hand into the bowl with Me\"','D',223,88,'Life of Christ','2021-10-19',24080,8446,'Approved',NULL,'2014-04-15 15:47:40','2021-10-19 17:11:41');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (1111,1,1,'mcq','','After Jesus and the disciples closed the Last Supper with a hymn, what mountain did they go to?','Calvary','Golgotha','Mount Moriah','Mount of Olives','D',226,81,'Life of Christ','2021-10-19',24087,8446,'Approved',NULL,'2014-04-15 15:51:53','2021-10-19 17:12:28');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (1112,1,1,'mcq','','Jesus said of the man who would betray Him that it would be better for that man if ____________________.','He had a millstone tied around his neck and was thrown into the sea.','He had died before betraying the Son of Man.','He had been from Sodom and Gomorrah on the Day of Judgment.','He had never been born.','D',196,82,'Quotations','2021-10-19',24081,8446,'Approved','Grammar','2014-04-15 15:56:58','2021-10-19 17:13:06');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (1254,1,1,'mcq','','Where was Jesus born? ','Derbe ','Bethlehem','Lystra','Rome','B',158,100,'Life of Christ','2021-10-16',23173,11911,'Approved','Spelling','2014-05-14 16:27:35','2021-10-16 23:05:42');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (1334,1,1,'mcq',NULL,'Why was David at the battle at which he fought Goliath?','To be King Saul\'s armourbearer','To bring his father an account of the battle','To watch the battle','To bring his brothers food','D',178,82,'History','2021-10-19',7638,7811,'Approved',NULL,'2014-05-30 04:51:00','2021-10-19 17:06:28');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (1335,1,1,'mcq',NULL,'Beside David, who else did King Saul throw a spear at?','Samuel','Eliab','Jonathan','Ahimelech','C',183,78,'History','2021-10-19',7766,7811,'Approved',NULL,'2014-05-30 05:06:23','2021-10-19 17:06:51');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (1337,1,1,'mcq','','The prophet Ezekiel prophesied that Israel would be attacked from which direction?','North','South','East','West','A',180,46,'Prophecy','2021-10-19',21443,29025,'Approved',NULL,'2014-05-30 19:54:36','2021-10-19 17:07:07');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (1338,1,1,'mcq','','The apostle Paul wrote to the Romans that Israel had experienced a hardening, in part, until ________________ .','they cease to be wise in their own eyes.','the great and terrible day of the Lord.','the Lord gives them beauty for ashes and oil of joy for mourning.','the fullness of the Gentiles had come in.','D',184,49,'Disciples & Apostles','2021-10-19',28237,29025,'Approved',NULL,'2014-05-30 19:57:12','2021-10-19 17:07:24');
INSERT INTO `quiz_questions` (`id`, `quiz_id`, `question_no`, `question_type`, `passage`, `mc_question`, `mc_option_a`, `mc_option_b`, `mc_option_c`, `mc_option_d`, `mc_answer`, `times_answered`, `perc_correct`, `mcq_category`, `last_asked`, `supporting_ref`, `submitted_by`, `approval_status`, `rejection_code`, `created_at`, `updated_at`) VALUES (2025,1,1,'mcq','','How many books of the Bible are categorized as minor prophets in the hebrew Bible?','9','10','11','12','D',176,37,'History','2021-10-19',22098,11843,'Approved',NULL,'2014-10-07 03:38:08','2021-10-19 17:06:11');
/*!40000 ALTER TABLE `quiz_questions` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2025-08-15 15:45:17

SET FOREIGN_KEY_CHECKS=1;

-- End of export
